In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
import sweetviz as sv
import numpy as np

import sys
sys.path.insert(1, '../utils')
from correlacion.correlacion import remove_highly_correlated_features

In [2]:
experiment_name = 'experiment_5'

## Preparar Datos

### Variable respuesta

In [44]:
data_y = pd.read_csv(r"..\data\{}\pmod_base_cruce.csv".format(experiment_name))
data_y.head()

,nit_enmascarado,num_oblig_enmascarado,num_oblig_orig_enmascarado,fecha_var_rpta_alt,var_rpta_alt,marca_pago,ajustes_banco,lote
0,144677,944034,144069,202311,0.0,NO_PAGO,NO,2.0
1,193430,470009,610333,202310,0.0,NO_PAGO,NO,2.0
2,61793,580684,499658,202401,NaN,FACTURACION_MES_SGTE,NO,2.0
3,198870,880527,204728,202310,0.0,IGUAL,NO,1.0
4,34986,54648,1025694,202311,0.0,NO_PAGO,NO,2.0

In [45]:
print("Cantidad de datos con valores infinitos: ", (data_y.isin([np.inf, -np.inf]).sum()).sum())
print("Cantidad de datos con valores nulos: ", (data_y.isna().sum()).sum())

Cantidad de datos con valores infinitos:  0
Cantidad de datos con valores nulos:  117055

In [46]:
data_y.isna().sum()

nit_enmascarado                    0
num_oblig_enmascarado              0
num_oblig_orig_enmascarado         0
fecha_var_rpta_alt                 0
var_rpta_alt                  112549
marca_pago                      1179
ajustes_banco                   1179
lote                            2148
dtype: int64

In [13]:
df_report = data_y[data_y["fecha_var_rpta_alt"] < 202401]
df_report = df_report.drop(columns=["nit_enmascarado", "num_oblig_enmascarado", "num_oblig_orig_enmascarado", "fecha_var_rpta_alt"])
report = sv.analyze([df_report, 'Train'], target_feat='var_rpta_alt')
report.show_html('data_analysis/data_analysis_y.html')

                                             |          | [  0%]   00:00 -> (? left)

Report data_analysis/data_analysis_y.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.

In [48]:
data_y["marca_pago"] = data_y["marca_pago"].fillna('NO_DATA')
data_y["marca_pago"] = data_y["marca_pago"].astype('category')

data_y["ajustes_banco"] = data_y["ajustes_banco"].fillna('NO_DATA')
data_y["ajustes_banco"] = data_y["ajustes_banco"].astype('category')

data_y["lote"] = data_y["lote"].fillna(-99)
data_y["lote"] = data_y["lote"].astype('int')

In [49]:
data_y.isna().sum()

nit_enmascarado                    0
num_oblig_enmascarado              0
num_oblig_orig_enmascarado         0
fecha_var_rpta_alt                 0
var_rpta_alt                  112549
marca_pago                         0
ajustes_banco                      0
lote                               0
dtype: int64

### Saldos diarios

In [14]:
data_sd = pd.read_csv(r"..\data\{}\pmod_tend_sd.csv".format(experiment_name))
data_sd.head()

,nit_enmascarado,num_oblig_enmascarado,num_oblig_orig_enmascarado,fecha_var_rpta_alt,avg_sld_cap_final_1,avg_sld_cap_final_avg_ult3,avg_sld_cap_final_avg_ult6,avg_sld_cap_final_stddev_ult3,avg_sld_cap_final_stddev_ult6,avg_sld_cap_final_max_ult6,avg_sld_cap_final_max_ult3,max_dia_sld_cap_final_1,max_dia_sld_cap_final_avg_ult3,max_dia_sld_cap_final_avg_ult6,max_dia_sld_cap_final_stddev_ult3,max_dia_sld_cap_final_stddev_ult6,max_dia_sld_cap_final_max_ult6,max_dia_sld_cap_final_max_ult3,min_sld_cap_final_1,min_sld_cap_final_avg_ult3,min_sld_cap_final_avg_ult6,min_sld_cap_final_stddev_ult3,min_sld_cap_final_stddev_ult6,min_sld_cap_final_max_ult6,min_sld_cap_final_max_ult3,avg_nueva_altura_mora_1,avg_nueva_altura_mora_avg_ult3,avg_nueva_altura_mora_avg_ult6,avg_nueva_altura_mora_stddev_ult3,avg_nueva_altura_mora_stddev_ult6,avg_nueva_altura_mora_max_ult6,avg_nueva_altura_mora_max_ult3,max_nueva_altura_mora_1,max_nueva_altura_mora_avg_ult3,max_nueva_altura_mora_avg_ult6,max_nueva_altura_mora_stddev_ult3,max_nueva_altura_mora_stddev_ult6,max_nueva_altura_mora_max_ult6,max_nueva_altura_mora_max_ult3,min_nueva_altura_mora_1,min_nueva_altura_mora_avg_ult3,min_nueva_altura_mora_avg_ult6,min_nueva_altura_mora_stddev_ult3,min_nueva_altura_mora_stddev_ult6,min_nueva_altura_mora_max_ult6,min_nueva_altura_mora_max_ult3,avg_vlr_obligacion_1,avg_vlr_obligacion_avg_ult3,avg_vlr_obligacion_avg_ult6,avg_vlr_obligacion_stddev_ult3,avg_vlr_obligacion_stddev_ult6,avg_vlr_obligacion_max_ult6,avg_vlr_obligacion_max_ult3,max_vlr_obligacion_1,max_vlr_obligacion_avg_ult3,max_vlr_obligacion_avg_ult6,max_vlr_obligacion_stddev_ult3,max_vlr_obligacion_stddev_ult6,max_vlr_obligacion_max_ult6,max_vlr_obligacion_max_ult3,min_vlr_obligacion_1,min_vlr_obligacion_avg_ult3,min_vlr_obligacion_avg_ult6,min_vlr_obligacion_stddev_ult3,min_vlr_obligacion_stddev_ult6,min_vlr_obligacion_max_ult6,min_vlr_obligacion_max_ult3,avg_vlr_vencido_1,avg_vlr_vencido_avg_ult3,avg_vlr_vencido_avg_ult6,avg_vlr_vencido_stddev_ult3,avg_vlr_vencido_stddev_ult6,avg_vlr_vencido_max_ult6,avg_vlr_vencido_max_ult3,max_vlr_vencido_1,max_vlr_vencido_avg_ult3,max_vlr_vencido_avg_ult6,max_vlr_vencido_stddev_ult3,max_vlr_vencido_stddev_ult6,max_vlr_vencido_max_ult6,max_vlr_vencido_max_ult3,min_vlr_vencido_1,min_vlr_vencido_avg_ult3,min_vlr_vencido_avg_ult6,min_vlr_vencido_stddev_ult3,min_vlr_vencido_stddev_ult6,min_vlr_vencido_max_ult6,min_vlr_vencido_max_ult3
0,54787,17230,1063112,202308,9396897.16,9.396905e+06,9.396921e+06,1.126809e+01,1.744234e+01,9396936.16,9.396921e+06,9396897.16,9.396910e+06,9.396923e+06,1.838478e+01,1.838478e+01,9396936.16,9396936.16,9396897.16,9396897.16,9.396917e+06,0.000000,1.950000e+01,9396936.16,9396897.16,12.451613,15.582796,10.602061,5.414502,7.356972,23.200000,23.200000,46,38.000000,26.333333,7.483315,14.452989,46,46,0,2.666667,1.333333,3.771236,2.981424,8,8,9.677539e+06,9.768763e+06,9.861808e+06,1.045753e+05,1.193481e+05,9.976320e+06,9.915184e+06,9818774,9.893408e+06,9.972290e+06,1.043017e+05,1.100866e+05,10081884,10040909,9579149,9.671161e+06,9.774358e+06,90082.413171,1.213063e+05,9882062,9793473,1.531166e+05,1.632562e+05,1.383508e+05,4.896006e+04,5.793276e+04,2.276431e+05,2.276431e+05,296389,2.912750e+05,2.861218e+05,7.123671e+03,7.206160e+03,296389,296389,51,5043.666667,2.521833e+03,7096.789900,5.616214e+03,15080,15080
1,146602,672802,407118,202401,2949134.31,3.001168e+06,3.055246e+06,4.061146e+04,7.162829e+04,3182493.22,3.048240e+06,2949134.31,3.029968e+06,3.091783e+06,6.081091e+04,8.065383e+04,3182493.22,3095809.34,2949134.31,2965769.24,3.029930e+06,59050.470194,8.839586e+04,3182493.22,3044959.10,43.161290,46.754122,27.659498,4.522783,19.758179,53.133333,53.133333,59,64.666667,44.166667,8.013877,23.405246,76,76,29,24.666667,12.333333,5.436502,12.918548,29,29,3.053774e+06,3.126353e+06,3.190597e+06,5.271633e+04,8.089675e+04,3.318837e+06,3.177398e+06,3094243,3.221787e+06,3.279087e+06,9.178355e+04,8.786145e+04,3351363,3306432,3010607,3.034895e+06,3.111721e+06,51445.190305,9.809772e+04,3279341,3106432,4.055197e+05,3.523807e+05,2.491328e+05,6.874209e+04,1.214375e+05,4.055197e+05,4.055197e+05,467376,4.368817e+05,3.456022e+05,1.079146e+05,1.215499e+05,551137,551137,251137,194676.000000,1.199372e+05,79847.911945,9.638677e+04,251137,251137
2,449080,855660,227160,202401,6899545.56,6.899546e+06,5.831331e+06,0.000000e+00,1.682165e+06,6899545.56,6.899546e+06,6899545.56,6.899546e+06,6.166889e+06,0.000000e+00,1.638270e+06,6899545.56,6899545.56,6899545.56,6899545.56,5.383222e+06,0.000000,2.144623e+06,6899545.56,6899545.56,43.161290,18.764875,10.093548,18.064882,15.504341,43.161290,43.161290,59,28.333333,16.833333,24.143092,21.263558,59,59,29,9.666667,4.833333,13.670731,10.807662,29,29,7.776939e+06,7.577340e+06,6.185934e+06,1.576554e+05,1.934567e+06,7.776939e+06,7.776939e+06,7878670,7.672980e+06,6.659207e+06,1.661172e+05,1.824156e+06,7878670,7878670,7668426,7.473507e+06,5.670203e+06,158474.934007,2.358948e+06,7668426,7668426,8.490816e+05,4.741773e+05,2.835599e+05,3.013391e+05,3.006259e+05,8.490816e+05,8.490816e+05,981724,5.843803e+05,4.052767e+05,3.225869e+05,3.677819e+05,981724,981724,579827,257139.000000,1.285695e+05,241208.541907,2.135905e+05,579827,579827
3,497069,248136,832206,202311,36562047.76,3.656205e+07,3.051209e+07,0.000000e+00,1.364557e+07,36735052.76,3.656205e+07,36562047.76,3.656205e+07,3.052604e+07,0.000000e+00,1.365188e+07,36735052.76,36562047.76,36562047.76,36562047.76,3.049721e+07,0.000000,1.363891e+07,36735052.76,36562047.76,56.483871,28.118280,14.059140,22.345882,21.150145,56.483871,56.483871,71,40.666667,20.333333,24.904261,26.898988,71,71,41,18.000000,9.000000,17.107503,15.077577,41,41,3.866522e+07,3.795559e+07,2.991228e+07,5.754048e+05,1.378800e+07,3.866522e+07,3.866522e+07,38975162,3.828685e+07,3.150193e+07,5.750175e+05,1.410464e+07,38975162,38975162,38317708,3.759937e+07,2.489726e+07,583168.747773,1.761350e+07,38317708,38317708,1.816646e+06,1.033069e+06,5.165345e+05,6.223971e+05,6.785993e+05,1.816646e+06,1.816646e+06,2283824,1.521635e+06,7.608175e+05,6.221611e+05,8.788546e+05,2283824,2283824,1521234,760377.000000,3.801885e+05,621041.272643,5.808523e+05,1521234,1521234
4,4291,453589,626753,202309,2034900.00,3.154857e+06,4.533265e+06,1.583858e+06,1.776038e+06,5911673.00,5.394770e+06,2034900.00,3.327158e+06,4.619415e+06,1.827528e+06,1.827528e+06,5911673.00,5911673.00,2034900.00,2034900.00,3.973286e+06,0.000000,1.938386e+06,5911673.00,2034900.00,1.000000,32.166667,41.633154,44.785290,37.442092,95.500000,95.500000,7,43.000000,54.666667,55.934485,44.615642,122,122,0,0.000000,18.000000,0.000000,25.185975,66,0,1.943411e+06,3.469903e+06,5.138406e+06,2.201939e+06,2.283973e+06,6.963812e+06,6.583717e+06,1970114,3.683736e+06,5.283187e+06,2.465919e+06,2.367809e+06,7170901,7170901,1912183,1.870379e+06,4.299272e+06,29570.829436,2.430905e+06,6888761,1912183,4.352452e+04,9.152102e+05,1.884323e+06,1.263651e+06,1.319655e+06,2.943754e+06,2.702106e+06,192982,1.073126e+06,1.992630e+06,1.383415e+06,1.343002e+06,3026395,3026395,0,0.000000,1.405516e+06,0.000000,1.407565e+06,2914138,0

In [15]:
print("Cantidad de valores:", data_sd.shape)
print("Cantidad de datos con valores infinitos: ", (data_sd.isin([np.inf, -np.inf]).sum()).sum())
print("Cantidad de datos con valores nulos: ", (data_sd.isna().sum()).sum())
print("Cantidad de datos con valores negativos: ", ((data_sd < 0).sum()).sum())

Cantidad de valores: (680800, 88)
Cantidad de datos con valores infinitos:  0
Cantidad de datos con valores nulos:  0
Cantidad de datos con valores negativos:  0

In [16]:
data_sd = pd.merge(data_sd, 
                   data_y[["nit_enmascarado","num_oblig_enmascarado","num_oblig_orig_enmascarado","fecha_var_rpta_alt",'var_rpta_alt']], 
                   on=["nit_enmascarado","num_oblig_enmascarado","num_oblig_orig_enmascarado","fecha_var_rpta_alt"], 
                   how='inner')
data_sd.head()

,nit_enmascarado,num_oblig_enmascarado,num_oblig_orig_enmascarado,fecha_var_rpta_alt,avg_sld_cap_final_1,avg_sld_cap_final_avg_ult3,avg_sld_cap_final_avg_ult6,avg_sld_cap_final_stddev_ult3,avg_sld_cap_final_stddev_ult6,avg_sld_cap_final_max_ult6,avg_sld_cap_final_max_ult3,max_dia_sld_cap_final_1,max_dia_sld_cap_final_avg_ult3,max_dia_sld_cap_final_avg_ult6,max_dia_sld_cap_final_stddev_ult3,max_dia_sld_cap_final_stddev_ult6,max_dia_sld_cap_final_max_ult6,max_dia_sld_cap_final_max_ult3,min_sld_cap_final_1,min_sld_cap_final_avg_ult3,min_sld_cap_final_avg_ult6,min_sld_cap_final_stddev_ult3,min_sld_cap_final_stddev_ult6,min_sld_cap_final_max_ult6,min_sld_cap_final_max_ult3,avg_nueva_altura_mora_1,avg_nueva_altura_mora_avg_ult3,avg_nueva_altura_mora_avg_ult6,avg_nueva_altura_mora_stddev_ult3,avg_nueva_altura_mora_stddev_ult6,avg_nueva_altura_mora_max_ult6,avg_nueva_altura_mora_max_ult3,max_nueva_altura_mora_1,max_nueva_altura_mora_avg_ult3,max_nueva_altura_mora_avg_ult6,max_nueva_altura_mora_stddev_ult3,max_nueva_altura_mora_stddev_ult6,max_nueva_altura_mora_max_ult6,max_nueva_altura_mora_max_ult3,min_nueva_altura_mora_1,min_nueva_altura_mora_avg_ult3,min_nueva_altura_mora_avg_ult6,min_nueva_altura_mora_stddev_ult3,min_nueva_altura_mora_stddev_ult6,min_nueva_altura_mora_max_ult6,min_nueva_altura_mora_max_ult3,avg_vlr_obligacion_1,avg_vlr_obligacion_avg_ult3,avg_vlr_obligacion_avg_ult6,avg_vlr_obligacion_stddev_ult3,avg_vlr_obligacion_stddev_ult6,avg_vlr_obligacion_max_ult6,avg_vlr_obligacion_max_ult3,max_vlr_obligacion_1,max_vlr_obligacion_avg_ult3,max_vlr_obligacion_avg_ult6,max_vlr_obligacion_stddev_ult3,max_vlr_obligacion_stddev_ult6,max_vlr_obligacion_max_ult6,max_vlr_obligacion_max_ult3,min_vlr_obligacion_1,min_vlr_obligacion_avg_ult3,min_vlr_obligacion_avg_ult6,min_vlr_obligacion_stddev_ult3,min_vlr_obligacion_stddev_ult6,min_vlr_obligacion_max_ult6,min_vlr_obligacion_max_ult3,avg_vlr_vencido_1,avg_vlr_vencido_avg_ult3,avg_vlr_vencido_avg_ult6,avg_vlr_vencido_stddev_ult3,avg_vlr_vencido_stddev_ult6,avg_vlr_vencido_max_ult6,avg_vlr_vencido_max_ult3,max_vlr_vencido_1,max_vlr_vencido_avg_ult3,max_vlr_vencido_avg_ult6,max_vlr_vencido_stddev_ult3,max_vlr_vencido_stddev_ult6,max_vlr_vencido_max_ult6,max_vlr_vencido_max_ult3,min_vlr_vencido_1,min_vlr_vencido_avg_ult3,min_vlr_vencido_avg_ult6,min_vlr_vencido_stddev_ult3,min_vlr_vencido_stddev_ult6,min_vlr_vencido_max_ult6,min_vlr_vencido_max_ult3,var_rpta_alt
0,54787,17230,1063112,202308,9396897.16,9.396905e+06,9.396921e+06,1.126809e+01,1.744234e+01,9396936.16,9.396921e+06,9396897.16,9.396910e+06,9.396923e+06,1.838478e+01,1.838478e+01,9396936.16,9396936.16,9396897.16,9396897.16,9.396917e+06,0.000000,1.950000e+01,9396936.16,9396897.16,12.451613,15.582796,10.602061,5.414502,7.356972,23.200000,23.200000,46,38.000000,26.333333,7.483315,14.452989,46,46,0,2.666667,1.333333,3.771236,2.981424,8,8,9.677539e+06,9.768763e+06,9.861808e+06,1.045753e+05,1.193481e+05,9.976320e+06,9.915184e+06,9818774,9.893408e+06,9.972290e+06,1.043017e+05,1.100866e+05,10081884,10040909,9579149,9.671161e+06,9.774358e+06,90082.413171,1.213063e+05,9882062,9793473,1.531166e+05,1.632562e+05,1.383508e+05,4.896006e+04,5.793276e+04,2.276431e+05,2.276431e+05,296389,2.912750e+05,2.861218e+05,7.123671e+03,7.206160e+03,296389,296389,51,5043.666667,2.521833e+03,7096.789900,5.616214e+03,15080,15080,1.0
1,146602,672802,407118,202401,2949134.31,3.001168e+06,3.055246e+06,4.061146e+04,7.162829e+04,3182493.22,3.048240e+06,2949134.31,3.029968e+06,3.091783e+06,6.081091e+04,8.065383e+04,3182493.22,3095809.34,2949134.31,2965769.24,3.029930e+06,59050.470194,8.839586e+04,3182493.22,3044959.10,43.161290,46.754122,27.659498,4.522783,19.758179,53.133333,53.133333,59,64.666667,44.166667,8.013877,23.405246,76,76,29,24.666667,12.333333,5.436502,12.918548,29,29,3.053774e+06,3.126353e+06,3.190597e+06,5.271633e+04,8.089675e+04,3.318837e+06,3.177398e+06,3094243,3.221787e+06,3.279087e+06,9.178355e+04,8.786145e+04,3351363,3306432,3010607,3.034895e+06,3.111721e+06,51445.190305,9.809772e+04,3279341,3106432,4.055197e+05,3.523807e+05,2.491328e+05,6.874209e+04,1.214375e+05,4.055197e+05,4.055197e+05,467376,4.368817e+05,3.456022e+05,1.079146e+05,1.215499e+05,551137,551137,251137,194676.000000,1.199372e+05,79847.911945,9.638677e+04,251137,251137,NaN
2,449080,855660,227160,202401,6899545.56,6.899546e+06,5.831331e+06,0.000000e+00,1.682165e+06,6899545.56,6.899546e+06,6899545.56,6.899546e+06,6.166889e+06,0.000000e+00,1.638270e+06,6899545.56,6899545.56,6899545.56,6899545.56,5.383222e+06,0.000000,2.144623e+06,6899545.56,6899545.56,43.161290,18.764875,10.093548,18.064882,15.504341,43.161290,43.161290,59,28.333333,16.833333,24.143092,21.263558,59,59,29,9.666667,4.833333,13.670731,10.807662,29,29,7.776939e+06,7.577340e+06,6.185934e+06,1.576554e+05,1.934567e+06,7.776939e+06,7.776939e+06,7878670,7.672980e+06,6.659207e+06,1.661172e+05,1.824156e+06,7878670,7878670,7668426,7.473507e+06,5.670203e+06,158474.934007,2.358948e+06,7668426,7668426,8.490816e+05,4.741773e+05,2.835599e+05,3.013391e+05,3.006259e+05,8.490816e+05,8.490816e+05,981724,5.843803e+05,4.052767e+05,3.225869e+05,3.677819e+05,981724,981724,579827,257139.000000,1.285695e+05,241208.541907,2.135905e+05,579827,579827,NaN
3,497069,248136,832206,202311,36562047.76,3.656205e+07,3.051209e+07,0.000000e+00,1.364557e+07,36735052.76,3.656205e+07,36562047.76,3.656205e+07,3.052604e+07,0.000000e+00,1.365188e+07,36735052.76,36562047.76,36562047.76,36562047.76,3.049721e+07,0.000000,1.363891e+07,36735052.76,36562047.76,56.483871,28.118280,14.059140,22.345882,21.150145,56.483871,56.483871,71,40.666667,20.333333,24.904261,26.898988,71,71,41,18.000000,9.000000,17.107503,15.077577,41,41,3.866522e+07,3.795559e+07,2.991228e+07,5.754048e+05,1.378800e+07,3.866522e+07,3.866522e+07,38975162,3.828685e+07,3.150193e+07,5.750175e+05,1.410464e+07,38975162,38975162,38317708,3.759937e+07,2.489726e+07,583168.747773,1.761350e+07,38317708,38317708,1.816646e+06,1.033069e+06,5.165345e+05,6.223971e+05,6.785993e+05,1.816646e+06,1.816646e+06,2283824,1.521635e+06,7.608175e+05,6.221611e+05,8.788546e+05,2283824,2283824,1521234,760377.000000,3.801885e+05,621041.272643,5.808523e+05,1521234,1521234,0.0
4,4291,453589,626753,202309,2034900.00,3.154857e+06,4.533265e+06,1.583858e+06,1.776038e+06,5911673.00,5.394770e+06,2034900.00,3.327158e+06,4.619415e+06,1.827528e+06,1.827528e+06,5911673.00,5911673.00,2034900.00,2034900.00,3.973286e+06,0.000000,1.938386e+06,5911673.00,2034900.00,1.000000,32.166667,41.633154,44.785290,37.442092,95.500000,95.500000,7,43.000000,54.666667,55.934485,44.615642,122,122,0,0.000000,18.000000,0.000000,25.185975,66,0,1.943411e+06,3.469903e+06,5.138406e+06,2.201939e+06,2.283973e+06,6.963812e+06,6.583717e+06,1970114,3.683736e+06,5.283187e+06,2.465919e+06,2.367809e+06,7170901,7170901,1912183,1.870379e+06,4.299272e+06,29570.829436,2.430905e+06,6888761,1912183,4.352452e+04,9.152102e+05,1.884323e+06,1.263651e+06,1.319655e+06,2.943754e+06,2.702106e+06,192982,1.073126e+06,1.992630e+06,1.383415e+06,1.343002e+06,3026395,3026395,0,0.000000,1.405516e+06,0.000000,1.407565e+06,2914138,0,0.0

In [18]:
df_report = data_sd[data_sd["fecha_var_rpta_alt"] < 202401]
df_report = df_report.drop(columns=["nit_enmascarado", "num_oblig_enmascarado", "num_oblig_orig_enmascarado", "fecha_var_rpta_alt"])
report = sv.analyze([df_report, 'Train'], target_feat='var_rpta_alt')
report.show_html('data_analysis/data_analysis_sd.html')

                                             |          | [  0%]   00:00 -> (? left)

Report data_analysis/data_analysis_sd.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.

In [17]:

data_sd_corr, to_drop = remove_highly_correlated_features(data_sd.drop(columns=["nit_enmascarado", "num_oblig_enmascarado", "num_oblig_orig_enmascarado", "fecha_var_rpta_alt", "var_rpta_alt"]),
                                                          threshold=0.8)

Variables eliminadas: ['avg_sld_cap_final_avg_ult3', 'avg_sld_cap_final_avg_ult6', 'avg_sld_cap_final_max_ult6', 'avg_sld_cap_final_max_ult3', 'max_dia_sld_cap_final_1', 'max_dia_sld_cap_final_avg_ult3', 'max_dia_sld_cap_final_avg_ult6', 'max_dia_sld_cap_final_stddev_ult3', 'max_dia_sld_cap_final_stddev_ult6', 'max_dia_sld_cap_final_max_ult6', 'max_dia_sld_cap_final_max_ult3', 'min_sld_cap_final_1', 'min_sld_cap_final_avg_ult3', 'min_sld_cap_final_avg_ult6', 'min_sld_cap_final_stddev_ult3', 'min_sld_cap_final_stddev_ult6', 'min_sld_cap_final_max_ult6', 'min_sld_cap_final_max_ult3', 'avg_nueva_altura_mora_avg_ult3', 'avg_nueva_altura_mora_avg_ult6', 'avg_nueva_altura_mora_stddev_ult6', 'avg_nueva_altura_mora_max_ult6', 'avg_nueva_altura_mora_max_ult3', 'max_nueva_altura_mora_1', 'max_nueva_altura_mora_avg_ult3', 'max_nueva_altura_mora_avg_ult6', 'max_nueva_altura_mora_stddev_ult3', 'max_nueva_altura_mora_stddev_ult6', 'max_nueva_altura_mora_max_ult6', 'max_nueva_altura_mora_max_ult3', 'min_nueva_altura_mora_1', 'min_nueva_altura_mora_avg_ult3', 'min_nueva_altura_mora_avg_ult6', 'min_nueva_altura_mora_stddev_ult3', 'min_nueva_altura_mora_stddev_ult6', 'min_nueva_altura_mora_max_ult6', 'min_nueva_altura_mora_max_ult3', 'avg_vlr_obligacion_1', 'avg_vlr_obligacion_avg_ult3', 'avg_vlr_obligacion_avg_ult6', 'avg_vlr_obligacion_stddev_ult3', 'avg_vlr_obligacion_stddev_ult6', 'avg_vlr_obligacion_max_ult6', 'avg_vlr_obligacion_max_ult3', 'max_vlr_obligacion_1', 'max_vlr_obligacion_avg_ult3', 'max_vlr_obligacion_avg_ult6', 'max_vlr_obligacion_stddev_ult3', 'max_vlr_obligacion_stddev_ult6', 'max_vlr_obligacion_max_ult6', 'max_vlr_obligacion_max_ult3', 'min_vlr_obligacion_1', 'min_vlr_obligacion_avg_ult3', 'min_vlr_obligacion_avg_ult6', 'min_vlr_obligacion_stddev_ult6', 'min_vlr_obligacion_max_ult6', 'min_vlr_obligacion_max_ult3', 'avg_vlr_vencido_avg_ult3', 'avg_vlr_vencido_avg_ult6', 'avg_vlr_vencido_stddev_ult3', 'avg_vlr_vencido_stddev_ult6', 'avg_vlr_vencido_max_ult6', 'avg_vlr_vencido_max_ult3', 'max_vlr_vencido_1', 'max_vlr_vencido_avg_ult3', 'max_vlr_vencido_avg_ult6', 'max_vlr_vencido_stddev_ult3', 'max_vlr_vencido_stddev_ult6', 'max_vlr_vencido_max_ult6', 'max_vlr_vencido_max_ult3', 'min_vlr_vencido_1', 'min_vlr_vencido_avg_ult3', 'min_vlr_vencido_avg_ult6', 'min_vlr_vencido_stddev_ult3', 'min_vlr_vencido_stddev_ult6', 'min_vlr_vencido_max_ult6', 'min_vlr_vencido_max_ult3']

In [18]:
data_sd = data_sd.drop(columns=to_drop)
print(data_sd.shape)
data_sd.head()

(680800, 12)

,nit_enmascarado,num_oblig_enmascarado,num_oblig_orig_enmascarado,fecha_var_rpta_alt,avg_sld_cap_final_1,avg_sld_cap_final_stddev_ult3,avg_sld_cap_final_stddev_ult6,avg_nueva_altura_mora_1,avg_nueva_altura_mora_stddev_ult3,min_vlr_obligacion_stddev_ult3,avg_vlr_vencido_1,var_rpta_alt
0,54787,17230,1063112,202308,9396897.16,1.126809e+01,1.744234e+01,12.451613,5.414502,90082.413171,1.531166e+05,1.0
1,146602,672802,407118,202401,2949134.31,4.061146e+04,7.162829e+04,43.161290,4.522783,51445.190305,4.055197e+05,NaN
2,449080,855660,227160,202401,6899545.56,0.000000e+00,1.682165e+06,43.161290,18.064882,158474.934007,8.490816e+05,NaN
3,497069,248136,832206,202311,36562047.76,0.000000e+00,1.364557e+07,56.483871,22.345882,583168.747773,1.816646e+06,0.0
4,4291,453589,626753,202309,2034900.00,1.583858e+06,1.776038e+06,1.000000,44.785290,29570.829436,4.352452e+04,0.0

### Maestro cuotas

In [19]:
data_mc = pd.read_csv(r"..\data\{}\pmod_tend_mc.csv".format(experiment_name))
data_mc.head()

,nit_enmascarado,num_oblig_enmascarado,num_oblig_orig_enmascarado,fecha_var_rpta_alt,valor_cuota_mes_1,valor_cuota_mes_avg_ult3,valor_cuota_mes_avg_ult6,valor_cuota_mes_stddev_ult3,valor_cuota_mes_stddev_ult6,valor_cuota_mes_max_ult6,valor_cuota_mes_max_ult3,pago_total_1,pago_total_avg_ult3,pago_total_avg_ult6,pago_total_stddev_ult3,pago_total_stddev_ult6,pago_total_max_ult6,pago_total_max_ult3,porc_pago_1,porc_pago_avg_ult3,porc_pago_avg_ult6,porc_pago_stddev_ult3,porc_pago_stddev_ult6,porc_pago_max_ult6,porc_pago_max_ult3
0,408272,653773,426206,202309,249579.0,315162.333333,345228.500000,101782.628830,130351.113387,564603.0,458921.0,0.0,761265.333333,484542.000000,1.058570e+06,824580.668833,2258236.0,2258236.0,0.0,167.666667,134.666667,229.382262,194.250411,492.0,492.0
1,114350,10571,1069771,202401,188172.0,188760.333333,188580.833333,416.419927,489.414077,189077.0,189077.0,0.0,125668.666667,313612.666667,1.777223e+05,401619.234703,1129002.0,377006.0,0.0,66.333333,166.333333,93.809500,213.073279,599.0,199.0
2,606576,482099,598243,202309,30452.0,40218.666667,40308.000000,13994.272217,14169.877958,60681.0,60009.0,121808.0,161049.333333,132635.000000,1.501034e+05,120198.248039,361340.0,361340.0,400.0,334.000000,337.333333,250.157284,241.815127,602.0,602.0
3,280731,527381,552961,202312,80151.0,53364.000000,48877.333333,21822.669085,18386.208705,80151.0,80151.0,0.0,17748.000000,26652.666667,2.509946e+04,26652.737237,53428.0,53244.0,0.0,33.333333,50.000000,47.140452,50.000000,100.0,100.0
4,41427,465205,615137,202309,257296.0,257300.000000,257304.166667,5.656854,9.026196,257320.0,257308.0,0.0,693333.333333,736666.666667,6.485539e+05,528950.743348,1560000.0,1560000.0,0.0,269.333333,286.166667,251.938264,205.477020,606.0,606.0

In [20]:
print("Cantidad de valores:", data_mc.shape[0])
print("Cantidad de datos con valores infinitos: ", (data_mc.isin([np.inf, -np.inf]).sum()).sum())
print("Cantidad de datos con valores nulos: ", (data_mc.isna().sum()).sum())
print("Cantidad de datos con valores negativos: ", ((data_mc < 0).sum()).sum())

Cantidad de valores: 680800
Cantidad de datos con valores infinitos:  2002
Cantidad de datos con valores nulos:  136985
Cantidad de datos con valores negativos:  0

In [21]:
data_mc.isin([np.inf, -np.inf]).sum()

nit_enmascarado                   0
num_oblig_enmascarado             0
num_oblig_orig_enmascarado        0
fecha_var_rpta_alt                0
valor_cuota_mes_1                 0
valor_cuota_mes_avg_ult3          0
valor_cuota_mes_avg_ult6          0
valor_cuota_mes_stddev_ult3       0
valor_cuota_mes_stddev_ult6       0
valor_cuota_mes_max_ult6          0
valor_cuota_mes_max_ult3          0
pago_total_1                      0
pago_total_avg_ult3               0
pago_total_avg_ult6               0
pago_total_stddev_ult3            0
pago_total_stddev_ult6            0
pago_total_max_ult6               0
pago_total_max_ult3               0
porc_pago_1                      31
porc_pago_avg_ult3              137
porc_pago_avg_ult6              537
porc_pago_stddev_ult3             0
porc_pago_stddev_ult6             0
porc_pago_max_ult6             1109
porc_pago_max_ult3              188
dtype: int64

In [22]:
data_mc.replace([np.inf, -np.inf], np.nan, inplace=True)

In [23]:
data_mc.isna().sum()

nit_enmascarado                    0
num_oblig_enmascarado              0
num_oblig_orig_enmascarado         0
fecha_var_rpta_alt                 0
valor_cuota_mes_1                  0
valor_cuota_mes_avg_ult3           0
valor_cuota_mes_avg_ult6           0
valor_cuota_mes_stddev_ult3        0
valor_cuota_mes_stddev_ult6        0
valor_cuota_mes_max_ult6           0
valor_cuota_mes_max_ult3           0
pago_total_1                       0
pago_total_avg_ult3                0
pago_total_avg_ult6                0
pago_total_stddev_ult3             0
pago_total_stddev_ult6             0
pago_total_max_ult6                0
pago_total_max_ult3                0
porc_pago_1                     8574
porc_pago_avg_ult3             18131
porc_pago_avg_ult6             37884
porc_pago_stddev_ult3          18131
porc_pago_stddev_ult6          37884
porc_pago_max_ult6              9652
porc_pago_max_ult3              8731
dtype: int64

In [24]:
data_mc = data_mc.fillna(-99)

In [25]:
data_mc = pd.merge(data_mc, 
                   data_y[["nit_enmascarado","num_oblig_enmascarado","num_oblig_orig_enmascarado","fecha_var_rpta_alt",'var_rpta_alt']], 
                   on=["nit_enmascarado","num_oblig_enmascarado","num_oblig_orig_enmascarado","fecha_var_rpta_alt"], 
                   how='inner')
data_mc.head()

,nit_enmascarado,num_oblig_enmascarado,num_oblig_orig_enmascarado,fecha_var_rpta_alt,valor_cuota_mes_1,valor_cuota_mes_avg_ult3,valor_cuota_mes_avg_ult6,valor_cuota_mes_stddev_ult3,valor_cuota_mes_stddev_ult6,valor_cuota_mes_max_ult6,valor_cuota_mes_max_ult3,pago_total_1,pago_total_avg_ult3,pago_total_avg_ult6,pago_total_stddev_ult3,pago_total_stddev_ult6,pago_total_max_ult6,pago_total_max_ult3,porc_pago_1,porc_pago_avg_ult3,porc_pago_avg_ult6,porc_pago_stddev_ult3,porc_pago_stddev_ult6,porc_pago_max_ult6,porc_pago_max_ult3,var_rpta_alt
0,408272,653773,426206,202309,249579.0,315162.333333,345228.500000,101782.628830,130351.113387,564603.0,458921.0,0.0,761265.333333,484542.000000,1.058570e+06,824580.668833,2258236.0,2258236.0,0.0,167.666667,134.666667,229.382262,194.250411,492.0,492.0,1.0
1,114350,10571,1069771,202401,188172.0,188760.333333,188580.833333,416.419927,489.414077,189077.0,189077.0,0.0,125668.666667,313612.666667,1.777223e+05,401619.234703,1129002.0,377006.0,0.0,66.333333,166.333333,93.809500,213.073279,599.0,199.0,NaN
2,606576,482099,598243,202309,30452.0,40218.666667,40308.000000,13994.272217,14169.877958,60681.0,60009.0,121808.0,161049.333333,132635.000000,1.501034e+05,120198.248039,361340.0,361340.0,400.0,334.000000,337.333333,250.157284,241.815127,602.0,602.0,1.0
3,280731,527381,552961,202312,80151.0,53364.000000,48877.333333,21822.669085,18386.208705,80151.0,80151.0,0.0,17748.000000,26652.666667,2.509946e+04,26652.737237,53428.0,53244.0,0.0,33.333333,50.000000,47.140452,50.000000,100.0,100.0,0.0
4,41427,465205,615137,202309,257296.0,257300.000000,257304.166667,5.656854,9.026196,257320.0,257308.0,0.0,693333.333333,736666.666667,6.485539e+05,528950.743348,1560000.0,1560000.0,0.0,269.333333,286.166667,251.938264,205.477020,606.0,606.0,1.0

In [44]:
df_report = data_mc[data_mc["fecha_var_rpta_alt"] < 202401]
df_report = df_report.drop(columns=["nit_enmascarado", "num_oblig_enmascarado", "num_oblig_orig_enmascarado", "fecha_var_rpta_alt"])
report = sv.analyze([df_report, 'Train'], target_feat='var_rpta_alt')
report.show_html('data_analysis/data_analysis_mc.html')

                                             |          | [  0%]   00:00 -> (? left)

Report data_analysis/data_analysis_mc.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.

In [26]:
data_mc_corr, to_drop = remove_highly_correlated_features(data_mc.drop(columns=["nit_enmascarado", "num_oblig_enmascarado", "num_oblig_orig_enmascarado", "fecha_var_rpta_alt", "var_rpta_alt"]),
                                                          threshold=0.8)

Variables eliminadas: ['valor_cuota_mes_avg_ult3', 'valor_cuota_mes_avg_ult6', 'valor_cuota_mes_max_ult6', 'valor_cuota_mes_max_ult3', 'pago_total_avg_ult6', 'pago_total_stddev_ult3', 'pago_total_stddev_ult6', 'pago_total_max_ult6', 'pago_total_max_ult3', 'porc_pago_avg_ult6', 'porc_pago_stddev_ult3', 'porc_pago_stddev_ult6', 'porc_pago_max_ult6', 'porc_pago_max_ult3']

In [27]:
data_mc = data_mc.drop(columns=to_drop)
print(data_mc.shape)
data_mc.head()

(680800, 12)

,nit_enmascarado,num_oblig_enmascarado,num_oblig_orig_enmascarado,fecha_var_rpta_alt,valor_cuota_mes_1,valor_cuota_mes_stddev_ult3,valor_cuota_mes_stddev_ult6,pago_total_1,pago_total_avg_ult3,porc_pago_1,porc_pago_avg_ult3,var_rpta_alt
0,408272,653773,426206,202309,249579.0,101782.628830,130351.113387,0.0,761265.333333,0.0,167.666667,1.0
1,114350,10571,1069771,202401,188172.0,416.419927,489.414077,0.0,125668.666667,0.0,66.333333,NaN
2,606576,482099,598243,202309,30452.0,13994.272217,14169.877958,121808.0,161049.333333,400.0,334.000000,1.0
3,280731,527381,552961,202312,80151.0,21822.669085,18386.208705,0.0,17748.000000,0.0,33.333333,0.0
4,41427,465205,615137,202309,257296.0,5.656854,9.026196,0.0,693333.333333,0.0,269.333333,1.0

### Master Customer Data

In [28]:
data_mcd = pd.read_csv(r"..\data\{}\pmod_tend_mcd.csv".format(experiment_name))
data_mcd.head()

,nit_enmascarado,num_oblig_enmascarado,num_oblig_orig_enmascarado,fecha_var_rpta_alt,total_ing_1,total_ing_avg_ult3,total_ing_avg_ult6,total_ing_stddev_ult3,total_ing_stddev_ult6,total_ing_max_ult6,total_ing_max_ult3,tot_activos_1,tot_activos_avg_ult3,tot_activos_avg_ult6,tot_activos_stddev_ult3,tot_activos_stddev_ult6,tot_activos_max_ult6,tot_activos_max_ult3,egresos_mes_1,egresos_mes_avg_ult3,egresos_mes_avg_ult6,egresos_mes_stddev_ult3,egresos_mes_stddev_ult6,egresos_mes_max_ult6,egresos_mes_max_ult3,tot_patrimonio_1,tot_patrimonio_avg_ult3,tot_patrimonio_avg_ult6,tot_patrimonio_stddev_ult3,tot_patrimonio_stddev_ult6,tot_patrimonio_max_ult6,tot_patrimonio_max_ult3
0,167120,117849,962493,202311,1010000.0,1010000.0,6.733333e+05,0.0,4.761186e+05,1010000.0,1010000.0,4.189000e+06,4.189000e+06,2.792667e+06,0.000000,1.974714e+06,4.189000e+06,4.189000e+06,200000.0,200000.0,1.333333e+05,0.00000,94280.904158,200000.0,200000.0,4.189000e+06,4.189000e+06,2.792667e+06,0.000000,1.974714e+06,4.189000e+06,4.189000e+06
1,365996,752619,26615,202401,17000000.0,17000000.0,1.700000e+07,0.0,0.000000e+00,17000000.0,17000000.0,7.000000e+07,7.000000e+07,7.000000e+07,0.000000,0.000000e+00,7.000000e+07,7.000000e+07,8000000.0,8000000.0,8.000000e+06,0.00000,0.000000,8000000.0,8000000.0,7.000000e+07,7.000000e+07,7.000000e+07,0.000000,0.000000e+00,7.000000e+07,7.000000e+07
2,579097,944907,143196,202309,0.0,0.0,0.000000e+00,0.0,0.000000e+00,0.0,0.0,1.174000e+06,7.826667e+05,3.913333e+05,553428.907409,5.534289e+05,1.174000e+06,1.174000e+06,1530000.0,1020000.0,5.100000e+05,721248.91681,721248.916810,1530000.0,1530000.0,1.174000e+06,7.826667e+05,3.913333e+05,553428.907409,5.534289e+05,1.174000e+06,1.174000e+06
3,596992,169088,911254,202311,3000000.0,3000000.0,2.000000e+06,0.0,1.414214e+06,3000000.0,3000000.0,6.000000e+07,6.000000e+07,4.000000e+07,0.000000,2.828427e+07,6.000000e+07,6.000000e+07,0.0,0.0,0.000000e+00,0.00000,0.000000,0.0,0.0,6.000000e+07,6.000000e+07,4.000000e+07,0.000000,2.828427e+07,6.000000e+07,6.000000e+07
4,311971,40897,1039445,202401,318760627.0,318760627.0,3.187606e+08,0.0,0.000000e+00,318760627.0,318760627.0,1.711490e+09,1.711490e+09,1.711490e+09,0.000000,0.000000e+00,1.711490e+09,1.711490e+09,11000000.0,11000000.0,1.100000e+07,0.00000,0.000000,11000000.0,11000000.0,1.262496e+09,1.262496e+09,1.262496e+09,0.000000,0.000000e+00,1.262496e+09,1.262496e+09

In [29]:
print("Cantidad de valores:", data_mcd.shape[0])
print("Cantidad de datos con valores infinitos: ", (data_mcd.isin([np.inf, -np.inf]).sum()).sum())
print("Cantidad de datos con valores nulos: ", (data_mcd.isna().sum()).sum())
print("Cantidad de datos con valores negativos: ", ((data_mcd < 0).sum()).sum())

Cantidad de valores: 680800
Cantidad de datos con valores infinitos:  0
Cantidad de datos con valores nulos:  2
Cantidad de datos con valores negativos:  0

In [30]:
data_mcd.isna().sum()

nit_enmascarado               0
num_oblig_enmascarado         0
num_oblig_orig_enmascarado    0
fecha_var_rpta_alt            0
total_ing_1                   0
total_ing_avg_ult3            0
total_ing_avg_ult6            0
total_ing_stddev_ult3         0
total_ing_stddev_ult6         0
total_ing_max_ult6            0
total_ing_max_ult3            0
tot_activos_1                 0
tot_activos_avg_ult3          0
tot_activos_avg_ult6          0
tot_activos_stddev_ult3       0
tot_activos_stddev_ult6       1
tot_activos_max_ult6          0
tot_activos_max_ult3          0
egresos_mes_1                 0
egresos_mes_avg_ult3          0
egresos_mes_avg_ult6          0
egresos_mes_stddev_ult3       0
egresos_mes_stddev_ult6       0
egresos_mes_max_ult6          0
egresos_mes_max_ult3          0
tot_patrimonio_1              0
tot_patrimonio_avg_ult3       0
tot_patrimonio_avg_ult6       0
tot_patrimonio_stddev_ult3    0
tot_patrimonio_stddev_ult6    1
tot_patrimonio_max_ult6       0
tot_patrimonio_max_ult3       0
dtype: int64

In [31]:
data_mcd = data_mcd.fillna(-99)

In [32]:
data_mcd = pd.merge(data_mcd, 
                   data_y[["nit_enmascarado","num_oblig_enmascarado","num_oblig_orig_enmascarado","fecha_var_rpta_alt",'var_rpta_alt']], 
                   on=["nit_enmascarado","num_oblig_enmascarado","num_oblig_orig_enmascarado","fecha_var_rpta_alt"], 
                   how='inner')
data_mcd.head()

,nit_enmascarado,num_oblig_enmascarado,num_oblig_orig_enmascarado,fecha_var_rpta_alt,total_ing_1,total_ing_avg_ult3,total_ing_avg_ult6,total_ing_stddev_ult3,total_ing_stddev_ult6,total_ing_max_ult6,total_ing_max_ult3,tot_activos_1,tot_activos_avg_ult3,tot_activos_avg_ult6,tot_activos_stddev_ult3,tot_activos_stddev_ult6,tot_activos_max_ult6,tot_activos_max_ult3,egresos_mes_1,egresos_mes_avg_ult3,egresos_mes_avg_ult6,egresos_mes_stddev_ult3,egresos_mes_stddev_ult6,egresos_mes_max_ult6,egresos_mes_max_ult3,tot_patrimonio_1,tot_patrimonio_avg_ult3,tot_patrimonio_avg_ult6,tot_patrimonio_stddev_ult3,tot_patrimonio_stddev_ult6,tot_patrimonio_max_ult6,tot_patrimonio_max_ult3,var_rpta_alt
0,167120,117849,962493,202311,1010000.0,1010000.0,6.733333e+05,0.0,4.761186e+05,1010000.0,1010000.0,4.189000e+06,4.189000e+06,2.792667e+06,0.000000,1.974714e+06,4.189000e+06,4.189000e+06,200000.0,200000.0,1.333333e+05,0.00000,94280.904158,200000.0,200000.0,4.189000e+06,4.189000e+06,2.792667e+06,0.000000,1.974714e+06,4.189000e+06,4.189000e+06,1.0
1,365996,752619,26615,202401,17000000.0,17000000.0,1.700000e+07,0.0,0.000000e+00,17000000.0,17000000.0,7.000000e+07,7.000000e+07,7.000000e+07,0.000000,0.000000e+00,7.000000e+07,7.000000e+07,8000000.0,8000000.0,8.000000e+06,0.00000,0.000000,8000000.0,8000000.0,7.000000e+07,7.000000e+07,7.000000e+07,0.000000,0.000000e+00,7.000000e+07,7.000000e+07,NaN
2,579097,944907,143196,202309,0.0,0.0,0.000000e+00,0.0,0.000000e+00,0.0,0.0,1.174000e+06,7.826667e+05,3.913333e+05,553428.907409,5.534289e+05,1.174000e+06,1.174000e+06,1530000.0,1020000.0,5.100000e+05,721248.91681,721248.916810,1530000.0,1530000.0,1.174000e+06,7.826667e+05,3.913333e+05,553428.907409,5.534289e+05,1.174000e+06,1.174000e+06,0.0
3,596992,169088,911254,202311,3000000.0,3000000.0,2.000000e+06,0.0,1.414214e+06,3000000.0,3000000.0,6.000000e+07,6.000000e+07,4.000000e+07,0.000000,2.828427e+07,6.000000e+07,6.000000e+07,0.0,0.0,0.000000e+00,0.00000,0.000000,0.0,0.0,6.000000e+07,6.000000e+07,4.000000e+07,0.000000,2.828427e+07,6.000000e+07,6.000000e+07,0.0
4,311971,40897,1039445,202401,318760627.0,318760627.0,3.187606e+08,0.0,0.000000e+00,318760627.0,318760627.0,1.711490e+09,1.711490e+09,1.711490e+09,0.000000,0.000000e+00,1.711490e+09,1.711490e+09,11000000.0,11000000.0,1.100000e+07,0.00000,0.000000,11000000.0,11000000.0,1.262496e+09,1.262496e+09,1.262496e+09,0.000000,0.000000e+00,1.262496e+09,1.262496e+09,NaN

In [50]:
df_report = data_mcd[data_mcd["fecha_var_rpta_alt"] < 202401]
df_report = df_report.drop(columns=["nit_enmascarado", "num_oblig_enmascarado", "num_oblig_orig_enmascarado", "fecha_var_rpta_alt"])
report = sv.analyze([df_report, 'Train'], target_feat='var_rpta_alt')
report.show_html('data_analysis/data_analysis_mcd.html')

                                             |          | [  0%]   00:00 -> (? left)

Report data_analysis/data_analysis_mcd.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.

In [33]:
data_mcd_corr, to_drop = remove_highly_correlated_features(data_mcd.drop(columns=["nit_enmascarado", "num_oblig_enmascarado", "num_oblig_orig_enmascarado", "fecha_var_rpta_alt", "var_rpta_alt"]),
                                                          threshold=0.8)

Variables eliminadas: ['total_ing_avg_ult6', 'total_ing_stddev_ult6', 'total_ing_max_ult6', 'total_ing_max_ult3', 'tot_activos_avg_ult3', 'tot_activos_avg_ult6', 'tot_activos_max_ult6', 'tot_activos_max_ult3', 'egresos_mes_avg_ult3', 'egresos_mes_avg_ult6', 'egresos_mes_stddev_ult6', 'egresos_mes_max_ult6', 'egresos_mes_max_ult3', 'tot_patrimonio_1', 'tot_patrimonio_avg_ult3', 'tot_patrimonio_avg_ult6', 'tot_patrimonio_max_ult6', 'tot_patrimonio_max_ult3']

In [34]:
data_mcd = data_mcd.drop(columns=to_drop)
print(data_mcd.shape)
data_mcd.head()

(680800, 15)

,nit_enmascarado,num_oblig_enmascarado,num_oblig_orig_enmascarado,fecha_var_rpta_alt,total_ing_1,total_ing_avg_ult3,total_ing_stddev_ult3,tot_activos_1,tot_activos_stddev_ult3,tot_activos_stddev_ult6,egresos_mes_1,egresos_mes_stddev_ult3,tot_patrimonio_stddev_ult3,tot_patrimonio_stddev_ult6,var_rpta_alt
0,167120,117849,962493,202311,1010000.0,1010000.0,0.0,4.189000e+06,0.000000,1.974714e+06,200000.0,0.00000,0.000000,1.974714e+06,1.0
1,365996,752619,26615,202401,17000000.0,17000000.0,0.0,7.000000e+07,0.000000,0.000000e+00,8000000.0,0.00000,0.000000,0.000000e+00,NaN
2,579097,944907,143196,202309,0.0,0.0,0.0,1.174000e+06,553428.907409,5.534289e+05,1530000.0,721248.91681,553428.907409,5.534289e+05,0.0
3,596992,169088,911254,202311,3000000.0,3000000.0,0.0,6.000000e+07,0.000000,2.828427e+07,0.0,0.00000,0.000000,2.828427e+07,0.0
4,311971,40897,1039445,202401,318760627.0,318760627.0,0.0,1.711490e+09,0.000000,0.000000e+00,11000000.0,0.00000,0.000000,0.000000e+00,NaN

### Probabilidades

In [35]:
data_pd = pd.read_csv(r"..\data\{}\pmod_tend_pd.csv".format(experiment_name))
data_pd.head()

,nit_enmascarado,num_oblig_enmascarado,num_oblig_orig_enmascarado,fecha_var_rpta_alt,prob_propension_1,prob_propension_avg_ult3,prob_propension_avg_ult6,prob_propension_stddev_ult3,prob_propension_stddev_ult6,prob_propension_max_ult6,prob_propension_max_ult3,prob_alrt_temprana_1,prob_alrt_temprana_avg_ult3,prob_alrt_temprana_avg_ult6,prob_alrt_temprana_stddev_ult3,prob_alrt_temprana_stddev_ult6,prob_alrt_temprana_max_ult6,prob_alrt_temprana_max_ult3,prob_auto_cura_1,prob_auto_cura_avg_ult3,prob_auto_cura_avg_ult6,prob_auto_cura_stddev_ult3,prob_auto_cura_stddev_ult6,prob_auto_cura_max_ult6,prob_auto_cura_max_ult3
0,544346,1027226,77860,202311,0.733868,0.777287,0.789446,0.032168,0.031598,0.835386,0.810754,0.471343,0.352104,0.283441,0.085434,0.108317,0.471343,0.471343,0.443394,0.691520,0.762811,0.175464,0.143347,0.850555,0.818133
1,194619,258342,822000,202312,0.846703,0.861044,0.849784,0.012593,0.020426,0.877358,0.877358,0.313214,0.301530,0.336077,0.011008,0.038270,0.395424,0.313214,0.723280,0.789793,0.824652,0.055878,0.054328,0.876294,0.860002
2,386545,646176,433978,202401,0.747076,0.768243,0.773170,0.030349,0.024214,0.811162,0.811162,0.437213,0.427688,0.369727,0.052670,0.071927,0.486903,0.486903,0.376739,0.537999,0.576964,0.127896,0.110928,0.700173,0.689568
3,510084,854406,228417,202308,0.766875,0.778772,0.782536,0.019211,0.017822,0.805873,0.805873,0.507313,0.487707,0.475447,0.055472,0.054062,0.543687,0.543687,0.409275,0.426047,0.392444,0.024984,0.038157,0.461365,0.461365
4,256444,567399,512943,202312,0.766753,0.858910,0.889944,0.065167,0.055735,0.926652,0.905670,0.699793,0.669000,0.531855,0.037302,0.163631,0.699793,0.699793,0.307203,0.371780,0.585487,0.055781,0.230931,0.878393,0.443307

In [36]:
print("Cantidad de valores:", data_pd.shape[0])
print("Cantidad de datos con valores infinitos: ", (data_pd.isin([np.inf, -np.inf]).sum()).sum())
print("Cantidad de datos con valores nulos: ", (data_pd.isna().sum()).sum())
print("Cantidad de datos con valores negativos: ", ((data_pd < 0).sum()).sum())

Cantidad de valores: 680800
Cantidad de datos con valores infinitos:  0
Cantidad de datos con valores nulos:  0
Cantidad de datos con valores negativos:  0

In [37]:
data_pd = pd.merge(data_pd, 
                   data_y[["nit_enmascarado","num_oblig_enmascarado","num_oblig_orig_enmascarado","fecha_var_rpta_alt",'var_rpta_alt']], 
                   on=["nit_enmascarado","num_oblig_enmascarado","num_oblig_orig_enmascarado","fecha_var_rpta_alt"], 
                   how='inner')
data_pd.head()

,nit_enmascarado,num_oblig_enmascarado,num_oblig_orig_enmascarado,fecha_var_rpta_alt,prob_propension_1,prob_propension_avg_ult3,prob_propension_avg_ult6,prob_propension_stddev_ult3,prob_propension_stddev_ult6,prob_propension_max_ult6,prob_propension_max_ult3,prob_alrt_temprana_1,prob_alrt_temprana_avg_ult3,prob_alrt_temprana_avg_ult6,prob_alrt_temprana_stddev_ult3,prob_alrt_temprana_stddev_ult6,prob_alrt_temprana_max_ult6,prob_alrt_temprana_max_ult3,prob_auto_cura_1,prob_auto_cura_avg_ult3,prob_auto_cura_avg_ult6,prob_auto_cura_stddev_ult3,prob_auto_cura_stddev_ult6,prob_auto_cura_max_ult6,prob_auto_cura_max_ult3,var_rpta_alt
0,544346,1027226,77860,202311,0.733868,0.777287,0.789446,0.032168,0.031598,0.835386,0.810754,0.471343,0.352104,0.283441,0.085434,0.108317,0.471343,0.471343,0.443394,0.691520,0.762811,0.175464,0.143347,0.850555,0.818133,1.0
1,194619,258342,822000,202312,0.846703,0.861044,0.849784,0.012593,0.020426,0.877358,0.877358,0.313214,0.301530,0.336077,0.011008,0.038270,0.395424,0.313214,0.723280,0.789793,0.824652,0.055878,0.054328,0.876294,0.860002,1.0
2,386545,646176,433978,202401,0.747076,0.768243,0.773170,0.030349,0.024214,0.811162,0.811162,0.437213,0.427688,0.369727,0.052670,0.071927,0.486903,0.486903,0.376739,0.537999,0.576964,0.127896,0.110928,0.700173,0.689568,NaN
3,510084,854406,228417,202308,0.766875,0.778772,0.782536,0.019211,0.017822,0.805873,0.805873,0.507313,0.487707,0.475447,0.055472,0.054062,0.543687,0.543687,0.409275,0.426047,0.392444,0.024984,0.038157,0.461365,0.461365,1.0
4,256444,567399,512943,202312,0.766753,0.858910,0.889944,0.065167,0.055735,0.926652,0.905670,0.699793,0.669000,0.531855,0.037302,0.163631,0.699793,0.699793,0.307203,0.371780,0.585487,0.055781,0.230931,0.878393,0.443307,1.0

In [58]:
df_report = data_pd[data_pd["fecha_var_rpta_alt"] < 202401]
df_report = df_report.drop(columns=["nit_enmascarado", "num_oblig_enmascarado", "num_oblig_orig_enmascarado", "fecha_var_rpta_alt"])
report = sv.analyze([df_report, 'Train'], target_feat='var_rpta_alt')
report.show_html('data_analysis/data_analysis_mcd.html')

                                             |          | [  0%]   00:00 -> (? left)

Report data_analysis/data_analysis_mcd.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.

In [38]:
data_pd_corr, to_drop = remove_highly_correlated_features(data_pd.drop(columns=["nit_enmascarado", "num_oblig_enmascarado", "num_oblig_orig_enmascarado", "fecha_var_rpta_alt", "var_rpta_alt"]),
                                                          threshold=0.8)

Variables eliminadas: ['prob_propension_avg_ult3', 'prob_propension_avg_ult6', 'prob_propension_max_ult3', 'prob_alrt_temprana_avg_ult3', 'prob_alrt_temprana_avg_ult6', 'prob_alrt_temprana_max_ult6', 'prob_alrt_temprana_max_ult3', 'prob_auto_cura_avg_ult3', 'prob_auto_cura_avg_ult6', 'prob_auto_cura_max_ult6', 'prob_auto_cura_max_ult3']

In [39]:
data_pd = data_pd.drop(columns=to_drop)
print(data_pd.shape)
data_pd.head()

(680800, 15)

,nit_enmascarado,num_oblig_enmascarado,num_oblig_orig_enmascarado,fecha_var_rpta_alt,prob_propension_1,prob_propension_stddev_ult3,prob_propension_stddev_ult6,prob_propension_max_ult6,prob_alrt_temprana_1,prob_alrt_temprana_stddev_ult3,prob_alrt_temprana_stddev_ult6,prob_auto_cura_1,prob_auto_cura_stddev_ult3,prob_auto_cura_stddev_ult6,var_rpta_alt
0,544346,1027226,77860,202311,0.733868,0.032168,0.031598,0.835386,0.471343,0.085434,0.108317,0.443394,0.175464,0.143347,1.0
1,194619,258342,822000,202312,0.846703,0.012593,0.020426,0.877358,0.313214,0.011008,0.038270,0.723280,0.055878,0.054328,1.0
2,386545,646176,433978,202401,0.747076,0.030349,0.024214,0.811162,0.437213,0.052670,0.071927,0.376739,0.127896,0.110928,NaN
3,510084,854406,228417,202308,0.766875,0.019211,0.017822,0.805873,0.507313,0.055472,0.054062,0.409275,0.024984,0.038157,1.0
4,256444,567399,512943,202312,0.766753,0.065167,0.055735,0.926652,0.699793,0.037302,0.163631,0.307203,0.055781,0.230931,1.0

 ### Base modelado

In [50]:
base_0 = pd.merge(data_y, 
         data_sd, 
         on=["nit_enmascarado","num_oblig_enmascarado","num_oblig_orig_enmascarado","fecha_var_rpta_alt", "var_rpta_alt"], 
         how='left')
base_1 = pd.merge(base_0, 
         data_mc, 
         on=["nit_enmascarado","num_oblig_enmascarado","num_oblig_orig_enmascarado","fecha_var_rpta_alt", "var_rpta_alt"], 
         how='left')
base_2 = pd.merge(base_1, 
         data_mcd, 
         on=["nit_enmascarado","num_oblig_enmascarado","num_oblig_orig_enmascarado","fecha_var_rpta_alt", "var_rpta_alt"], 
         how='left')
base_model = pd.merge(base_2, 
            data_pd, 
            on=["nit_enmascarado","num_oblig_enmascarado","num_oblig_orig_enmascarado","fecha_var_rpta_alt", "var_rpta_alt"], 
            how='left')

base_model.head()

,nit_enmascarado,num_oblig_enmascarado,num_oblig_orig_enmascarado,fecha_var_rpta_alt,var_rpta_alt,marca_pago,ajustes_banco,lote,avg_sld_cap_final_1,avg_sld_cap_final_stddev_ult3,avg_sld_cap_final_stddev_ult6,avg_nueva_altura_mora_1,avg_nueva_altura_mora_stddev_ult3,min_vlr_obligacion_stddev_ult3,avg_vlr_vencido_1,valor_cuota_mes_1,valor_cuota_mes_stddev_ult3,valor_cuota_mes_stddev_ult6,pago_total_1,pago_total_avg_ult3,porc_pago_1,porc_pago_avg_ult3,total_ing_1,total_ing_avg_ult3,total_ing_stddev_ult3,tot_activos_1,tot_activos_stddev_ult3,tot_activos_stddev_ult6,egresos_mes_1,egresos_mes_stddev_ult3,tot_patrimonio_stddev_ult3,tot_patrimonio_stddev_ult6,prob_propension_1,prob_propension_stddev_ult3,prob_propension_stddev_ult6,prob_propension_max_ult6,prob_alrt_temprana_1,prob_alrt_temprana_stddev_ult3,prob_alrt_temprana_stddev_ult6,prob_auto_cura_1,prob_auto_cura_stddev_ult3,prob_auto_cura_stddev_ult6
0,144677,944034,144069,202311,0.0,NO_PAGO,NO,2,3.951733e+06,2.688497e-10,3.292723e-10,73.967742,24.841908,96947.942534,610988.290323,1160581.0,315448.164749,353445.020129,0.0,0.000000,0.0,0.000000,5533000.0,6.523000e+06,700035.713375,56705000.0,1.317576e+06,2.576177e+07,722489.0,0.0,1.317576e+06,2.576177e+07,0.150296,0.059518,0.070604,0.291182,0.610527,0.005498,0.006131,0.107347,0.022619,0.053240
1,193430,470009,610333,202310,0.0,NO_PAGO,NO,2,1.966792e+06,0.000000e+00,0.000000e+00,64.000000,24.064492,46825.970418,181750.300000,212381.0,57832.455317,57802.501631,0.0,0.000000,0.0,0.000000,3400000.0,3.400000e+06,0.000000,51300000.0,0.000000e+00,2.565000e+07,1000000.0,0.0,0.000000e+00,1.815000e+07,0.317733,0.113442,0.099240,0.570639,0.735915,0.109572,0.087123,0.154782,0.076645,0.062913
2,61793,580684,499658,202401,NaN,FACTURACION_MES_SGTE,NO,2,1.809671e+06,1.615452e+04,3.753123e+04,1.000000,0.471405,15377.848376,10859.225806,48787.0,151.792256,161.978051,8172.0,133037.333333,17.0,272.000000,10865904.0,1.086590e+07,0.000000,70000000.0,0.000000e+00,0.000000e+00,0.0,0.0,0.000000e+00,0.000000e+00,0.925839,0.003060,0.002408,0.925839,0.378441,0.091614,0.085733,0.622551,0.013563,0.056557
3,198870,880527,204728,202310,0.0,IGUAL,NO,1,6.903930e+06,8.916558e+04,1.069897e+05,6.100000,5.364376,296681.795027,257228.966667,900672.0,223204.180619,223850.442124,901000.0,474327.000000,100.0,51.333333,2882000.0,2.882000e+06,0.000000,49076000.0,0.000000e+00,2.453800e+07,400000.0,0.0,0.000000e+00,2.403800e+07,0.683860,0.034618,0.055728,0.842226,0.609034,0.074364,0.155149,0.193738,0.086574,0.271958
4,34986,54648,1025694,202311,0.0,NO_PAGO,NO,2,3.128086e+06,2.688497e-10,1.474594e+06,52.483871,21.296844,68942.182622,184937.870968,249236.0,67877.405707,88652.936332,0.0,0.000000,0.0,0.000000,983166.0,9.221107e+05,86345.280455,13702225.0,0.000000e+00,6.459291e+06,800000.0,0.0,0.000000e+00,6.459291e+06,0.223442,0.219012,0.322461,0.755401,0.667432,0.193993,0.268648,0.240964,0.121755,0.203829

In [52]:
print("Cantidad de valores:", base_model.shape)
print("Cantidad de datos con valores infinitos: ", (base_model.isin([np.inf, -np.inf]).sum()).sum())
print("Cantidad de datos con valores nulos: ", (base_model.isna().sum()).sum())

Cantidad de valores: (680800, 42)
Cantidad de datos con valores infinitos:  0
Cantidad de datos con valores nulos:  112549

In [54]:
base_model.isna().sum()

nit_enmascarado                           0
num_oblig_enmascarado                     0
num_oblig_orig_enmascarado                0
fecha_var_rpta_alt                        0
var_rpta_alt                         112549
marca_pago                                0
ajustes_banco                             0
lote                                      0
avg_sld_cap_final_1                       0
avg_sld_cap_final_stddev_ult3             0
avg_sld_cap_final_stddev_ult6             0
avg_nueva_altura_mora_1                   0
avg_nueva_altura_mora_stddev_ult3         0
min_vlr_obligacion_stddev_ult3            0
avg_vlr_vencido_1                         0
valor_cuota_mes_1                         0
valor_cuota_mes_stddev_ult3               0
valor_cuota_mes_stddev_ult6               0
pago_total_1                              0
pago_total_avg_ult3                       0
porc_pago_1                               0
porc_pago_avg_ult3                        0
total_ing_1                               0
total_ing_avg_ult3                        0
total_ing_stddev_ult3                     0
tot_activos_1                             0
tot_activos_stddev_ult3                   0
tot_activos_stddev_ult6                   0
egresos_mes_1                             0
egresos_mes_stddev_ult3                   0
tot_patrimonio_stddev_ult3                0
tot_patrimonio_stddev_ult6                0
prob_propension_1                         0
prob_propension_stddev_ult3               0
prob_propension_stddev_ult6               0
prob_propension_max_ult6                  0
prob_alrt_temprana_1                      0
prob_alrt_temprana_stddev_ult3            0
prob_alrt_temprana_stddev_ult6            0
prob_auto_cura_1                          0
prob_auto_cura_stddev_ult3                0
prob_auto_cura_stddev_ult6                0
dtype: int64

In [55]:
df_report = base_model[base_model["fecha_var_rpta_alt"] < 202401]
df_report = df_report.drop(columns=["nit_enmascarado", "num_oblig_enmascarado", "num_oblig_orig_enmascarado", "fecha_var_rpta_alt"])
report = sv.analyze([df_report, 'Train'], target_feat='var_rpta_alt')
report.show_html('data_analysis/base_model.html')

                                             |          | [  0%]   00:00 -> (? left)

Report data_analysis/base_model.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.

In [56]:
base_model.to_csv(r"..\data\{}\pmod_base_model.csv".format(experiment_name), index=False)

In [58]:
print("Cantidad de valores:", base_model.shape)
print("Cantidad de datos con valores infinitos: ", (base_model.isin([np.inf, -np.inf]).sum()).sum())
print("Cantidad de datos con valores nulos: ", (base_model[base_model["fecha_var_rpta_alt"] < 202401].isna().sum()).sum())
# print("Cantidad de datos con valores negativos: ", ((base_model.drop(columns=["marca_pago"]) < 0).sum()).sum())

Cantidad de valores: (680800, 42)
Cantidad de datos con valores infinitos:  0
Cantidad de datos con valores nulos:  0